id: https://processieve.com/schemas/v0#
name: processieve
prefixes:
  linkml: https://w3id.org/linkml/
  prs: https://processieve.com/schemas/v0#

default_prefix: prs
default_range: string
imports:
  - linkml:types
enums:
  Status:
    permissible_values:
      draft:
      current:
      superseded:
types:
  JSON:
    uri: xsd:string
    base: str
    description: JSON data
  JSONSchema:
    uri: xsd:string
    base: str
    description: A Json schema
classes:
  Person:
    description: A person involved in a process
    slots:
      - id
      - name
    attributes:
      email:
        required: true
      skills:
        range: Proficiency
        multivalued: true
        # punting evidence

  Organization:
    description: An organization where persons work
    slots:
      - id
      - name
    attributes:
      mission_statetement:
      base_narrative:
        range: Narrative
      subunits:
        range: Organization
        multivalued: true
      casebook:
        range: Case
        multivalued: true
      rulebook:
        description: The best practice workbook of the organization
        range: Rulebook
        required: true
      considered_rules:
        range: Rulebook
        required: true
      personnel:
        range: Person
        multivalued: true
      core_programs:
        range: ProgramTemplate
        multivalued: true

  Rulebook:
    # Not putting an Id yet, I expect we'll use the Id of the Organization + status
    description: A set of rules
    slots:
      - status
    attributes:
      rules:
        range: Rule
        multivalued: true

  Case:
    description: The narrative description of an individual work unit we have solved or intend to solve.
    slots:
      - id
      - name
      - narratives
    attributes:
      idealized:
        range: boolean
        required: true
      selected_template:
        range: Rule
      considered_templates:
        range: Rule
        multivalued: true
      brief:
        range: Narrative
        multivalued: true
        required: true
      outcome:
        range: Report
        multivalued: true
      outcome_analysis:
        range: JSON

  Report:
    description: A report contains a narrative and evaluations
    attributes:
      based_on:
        range: ReportTemplate
    slots:
      - id
      - narrative
      - evaluations

  Skill:
    description: A requisite skill to fulfill a role in a process
    slots:
      - id
      - name
      - description
    attributes:
      requisites:
        range: Skill
        multivalued: true

  Proficiency:
    description: A level of proficiency in a skill
    attributes:
      level:
        range: float
        required: true
      skill:
        range: Skill
        required: true

  Rule:
    description:
      The template that describes an entry in our best practice workbook,
      consisting of an (abstracted) situation we try to solve, and the process we intend to use to solve it.
    slots:
      - id
      - name
      - description
      - prompt
    attributes:
      process:
        range: ProgramTemplate
      # expected_outcome:
      #   range: ReportTemplate
      superseded_by:
        range: Rule
      situation_condition:
        range: SituationCondition
        required: true

  Template:
    description: A schema that can be applied to a story
    abstract: true
    slots:
      - id
      - prompt
      - schema_def
      - narrative

  SituationSchema:
    description: A schema that describes questions applicable to a certain type of situation
    is_a: Template

  SituationCondition:
    description: Given that a situation fits a schema, what range of answers make a given rule applicable?
    slots:
      - id
    attributes:
      condition:
        range: JSON
        required: true
        description: |
          an ordered list of: situation min-max ranges, situation comprehension, score for each attribute in the situation schema, and a corresponding applicability score.
          Example of condition: [
          {
          "ranges": {"param1": [3, 4]},
          "lists": {"param2": [true], "param3": ['enum1', 'enum4']},
          "score": 1.0},
          {
          "ranges": {"param1": [1, 6]},
          "lists": {"param2": [true], "param3": ['enum1', 'enum4', 'enum5']},
          "score": 0.8},
          ]
      situation_schema:
        range: SituationSchema
        required: true

  Objective:
    slots:
      - id
    attributes:
      addresses:
        range: Criterion
        required: true
      standard_of_evalution:
      threshold:
        range: float

  ReportTemplate:
    is_a: Template
    description:
      A template that describes a category of outcome we expect at the end of a ProcessTemplate,
      and especially the criteria we intend to measure at the end of the process.
    attributes:
      objectives:
        range: Objective
        multivalued: true

  ProgramTemplate:
    description: The actual process we will use to solve a given problem.
    slots:
      - id
      - name
      - narrative
    attributes:
      roles:
        range: Role
        multivalued: true
      subprocesses:
        range: ProgramTemplate
        multivalued: true
      follows_process:
        range: ProgramTemplate
      outcome:
        range: ReportTemplate
        required: true

  Role:
    description: A process involves certain actors playing certain roles in the process. This describes the roles.
    slots:
      - id
      - name
      - description
    attributes:
      skills:
        range: Proficiency
        multivalued: true

  Narrative:
    description: A narrative description of either a concrete or abstracted Case or ProgramTemplate. There can be many narratives.
    slots:
      - id
      - authors
      - status
      - when
    attributes:
      title:
      content:

  Criterion:
    description:
      A description of a criterion by which outcomes will be evaluated.
      E.g. A KPI is a Criterion.
    slots:
      - id
      - name
      - description
    attributes:
      unit:

  Evaluation:
    # Not putting an Id, I expect we'll use the Id of the Objective
    description: The evaluation of an outcome with respect to one of the Program's Criteria
    attributes:
      objective:
        range: Objective
        required: true
      value:
        range: float
        required: true
      achieved:
        range: boolean
        required: true

slots:
  id:
    range: ncname
    identifier: true
    required: true
  name:
    required: true
  authors:
    multivalued: true
    range: Person
  description:
  evaluations:
    range: Evaluation
    multivalued: true
  narrative:
    range: Narrative
    required: true
  narratives:
    range: Narrative
    multivalued: true
  status:
    range: Status
    ifabsent: Status(draft)
  when:
    range: datetime
    required: true
  prompt:
  schema_def:
    range: JSONSchema
