id: https://processieve.com/schemas/v0#
name: processieve
prefixes:
  linkml: https://w3id.org/linkml/
  prs: https://processieve.com/schemas/v0#

default_prefix: prs
default_range: string
imports:
  - linkml:types
enums:
  Status:
    permissible_values:
      draft:
      current:
      superseded:
types:
  JSON:
    uri: xsd:string
    base: str
    description: JSON data
  JSONSchema:
    uri: xsd:string
    base: str
    description: A Json schema
classes:
  Person:
    description: A person involved in a process
    slots:
      - id
      - name
    attributes:
      email:
        required: true

  Organization:
    description: An organization where persons work
    slots:
      - id
      - name
    attributes:
      base_narrative:
        range: Narrative
      subunits:
        range: Organization
        multivalued: true
      cases:
        range: Case
        multivalued: true
      case_templates:
        description: The best practice workbook of the organization
        range: ProgramTemplate
        multivalued: true

  Case:
    description:
      The narrative description of an individual work unit we have solved or intend to solve.
    slots:
      - id
      - name
      - narratives
    attributes:
      selected_template:
        range: ProgramTemplate
      considered_templates:
        range: ProgramTemplate
        multivalued: true
      brief:
        range: Narrative
        multivalued: true
      reports:
        range: Narrative
        multivalued: true
      outcome:
        range: Narrative
        multivalued: true
      outcome_analysis:
        range: JSON
      evaluations:
        range: Evaluation
        multivalued: true

  ProgramTemplate:
    description:
      The template that describes an entry in our best practice workbook,
      consisting of an (abstracted) situation we try to solve, and the process we intend to use to solve it.
    slots:
      - id
      - name
      - authors
      - description
      - status
      - schema_def
      - prompt
    attributes:
      process:
        range: Process
      addresses:
        range: Criterion
        multivalued: true
      expected_outcome:
        range: OutcomeTemplate
      superseded_by:
        range: ProgramTemplate

  OutcomeTemplate:
    description:
      A template that describes a category of outcome we expect at the end of a ProcessTemplate,
      and especially the criteria we intend to measure at the end of the process.
    slots:
      - id
      - prompt
      - schema_def

  Process:
    description:
      The actual process we will use to solve a given problem.
    slots:
      - id
      - name
      - authors
      - description
      - status
    attributes:
      roles:
        range: Role
        multivalued: true
      subprocesses:
        range: Process
        multivalued: true
      follows_process:
        range: Process

  Role:
    description:
      A process involves certain actors playing certain roles in the process. This describes the roles.
    slots:
      - id
      - name
      - description
  Narrative:
    description:
      A narrative description of either a concrete or abstracted Case or Process. There can be many narratives.
    slots:
      - id
      - authors
      - status
      - when
    attributes:
      title:
      content:

  Criterion:
    description:
      A description of a criterion by which outcomes will be evaluated.
      E.g. A KPI is a Criterion.
    slots:
      - id
      - name
      - description
    attributes:
      unit:

  Evaluation:
    description:
      The evaluation of an outcome with respect to one of the Program's Criteria
    attributes:
      criterion:
        range: Criterion
      value:
        range: float
      standard_of_evaluation:
        # Might be worth defining a new object

slots:
  id:
    range: ncname
    identifier: true
    required: true
  name:
    required: true
  authors:
    multivalued: true
    range: Person
  description:
  narratives:
   range: Narrative
   multivalued: true
  status:
   range: Status
   ifabsent: Status(draft)
  when:
   range: datetime
   required: true
  prompt:
  schema_def:
    range: JSONSchema
